services:
  app:
    container_name: erdmaschine_app
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://db/postgres?user=postgres&password=postgres"

  db:
    container_name: erdmaschine_db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
