package erdmaschine.bot.model

val Fallacies = mapOf(
    "ad-hominem" to "Attacked the opponent instead of the argument",
    "affirming-consequent" to "Just because A follows B, B must not necessarily follow A",
    "anecdotal-evidence" to "Personal experience provided as proof",
    "appeal-to-authority" to "Proclaimed an expert in a field is infallible",
    "coincidence" to "Coincidence substituted for proof",
    "divine" to "Just because it fits your beliefs must not make it true",
    "equivocation" to "Homonym used to draw conclusion between different meanings",
    "false-dichotomy" to "Implying there are only to sides/options",
    "false-premise" to "Assumed the premise is true without proof",
    "generalization" to "Too small sample size to provide proper generalization",
    "goalpost" to "Changing the scope of the argument",
    "godwin" to "Too many hitlers on the field",
    "grammar" to "Attacked the grammer or spelling instead of the argument",
    "ignorance" to "Just because it hasn't been proven false doesn't mean it's true",
    "lack-of-evidence" to "Based conclusion on lack of evidence",
    "nirvana" to "Refusal to accept any solution that is not perfect",
    "personal-incredulity" to "Stating the opposing argument is wrong because one doesn't like or understand it",
    "red-herring" to "Attempt to derail the conversation with irrelevant points",
    "relative-privation" to "Just because someone else did something worse, doesn't make what you are doing right",
    "repetition" to "Repeating the same argument over and over again",
    "slippery-slope" to "No strictly necessary connection between cause and effect",
    "tradition" to "Just because that's the way we always did it doesn't mean it's the right way",
    "truescotsman" to "Arbitrarily defining group membership conditions to exclude a subset",
    "tuquoque" to "Just because someone is a hypocrite doesn't negate the point",
    "whataboutism" to "Attempt to discredit claim by pointing to something else without adressing the initial claim",
)
